# Generated by Django 5.1.7 on 2026-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
