[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn backend.wsgi --bind 0.0.0.0:$PORT --workers 4"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

