services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: uvicorn backend.asgi:application --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - fromDatabase:
          name: neondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
    healthCheckPath: /health/
    autoDeploy: false
