services:
  - type: web
    name: django-api
    env: python
buildCommand: apt-get update && apt-get install -y gcc python3-dev && pip install --no-cache-dir --upgrade pip setuptools wheel meson ninja && pip install -r requirements.txt && python backend/manage.py collectstatic --noinput --clear
    startCommand: gunicorn backend.wsgi:application --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - fromDatabase:
          name: neondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
    healthCheckPath: /health/
    autoDeploy: false
