services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --workers 1 --threads 4 --timeout 120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - fromDatabase:
          name: neondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
    healthCheckPath: /health/
    autoDeploy: false
